import os
from pathlib import Path

from validator.infrastructure.service_constants import PROD_CONTENT_BASE_URL


EXAMPLE_PROMPTS_PATH = Path(__file__).with_name("example_prompts.json")

PERCENTAGE_OF_TASKS_THAT_SHOULD_BE_INSTRUCT_TEXT = 0.75
PERCENTAGE_OF_INSTRUCT_TASKS_THAT_SHOULD_BE_CHAT = 0.5
PERCENTAGE_OF_TASKS_THAT_SHOULD_BE_IMAGE = 0.15
PERCENTAGE_OF_TASKS_THAT_SHOULD_BE_DPO = 0.20
# GRPO is the remainder of the text split (image is selected independently).
PERCENTAGE_OF_TASKS_THAT_SHOULD_BE_GRPO = (
    1
    - PERCENTAGE_OF_TASKS_THAT_SHOULD_BE_INSTRUCT_TEXT
    - PERCENTAGE_OF_TASKS_THAT_SHOULD_BE_DPO
)

INSTRUCT_KL_TASK_PROBABILITY = 0.2
INSTRUCT_KL_COEFFICIENT_MIN = 0.1
INSTRUCT_KL_COEFFICIENT_MAX = 1.5

TEXT_SYNTH_MODEL = "Qwen/Qwen3-32B"
TEXT_SYNTH_MODEL_TEMPERATURE = 0.6
TEXT_SYNTH_MODEL_MAX_TOKENS = 5024
END_OF_REASONING_TAG = "</think>"

IMAGE_PROMPT_GEN_MODEL = "Qwen/Qwen3-32B"
IMAGE_PROMPT_GEN_MODEL_TEMPERATURE = 0.4
IMAGE_PROMPT_GEN_MODEL_MAX_TOKENS = 5024
IMAGE_STYLE_PICKING_NUM_TRIES = 10
PERSON_GEN_RETRIES = 3
IMAGE_SYNTH_FACE_IMAGE_URL = "https://thispersondoesnotexist.com/"
PERCENTAGE_OF_IMAGE_SYNTHS_SHOULD_BE_STYLE = 0.5
PROBABILITY_STYLE_COMBINATION = 0.5
PERSON_SYNTH_DS_PREFIX = "person"
IMAGE_SYNTH_CATEGORY_STYLE = "style"
IMAGE_SYNTH_CATEGORY_PERSON = "person"
IMAGE_SYNTH_CATEGORY_LOGO = "logo"
IMAGE_SYNTH_CATEGORY_SOCIAL = "social"
IMAGE_SYNTH_CATEGORY_DESIGN = "design"
IMAGE_SYNTH_CATEGORY_PRODUCT = "product"
IMAGE_SYNTH_CATEGORY_WEIGHTS = {
    IMAGE_SYNTH_CATEGORY_STYLE: 0.25,
    IMAGE_SYNTH_CATEGORY_PERSON: 0.25,
    IMAGE_SYNTH_CATEGORY_LOGO: 0.15,
    IMAGE_SYNTH_CATEGORY_SOCIAL: 0.15,
    IMAGE_SYNTH_CATEGORY_DESIGN: 0.10,
    IMAGE_SYNTH_CATEGORY_PRODUCT: 0.10,
}
LOGO_SYNTH_DS_PREFIX = "logo"
SOCIAL_SYNTH_DS_PREFIX = "social"
DESIGN_SYNTH_DS_PREFIX = "design"
PRODUCT_SYNTH_DS_PREFIX = "product"

IMAGE_GEN_MODEL = "FLUX.1-schnell"
IMAGE_GEN_STEPS = 8
IMAGE_GEN_CFG_SCALE = 3

MIN_IMAGE_SYNTH_PAIRS = 10
MAX_IMAGE_SYNTH_PAIRS = 50

MIN_IMAGE_WIDTH = 1024
MAX_IMAGE_WIDTH = 1024
MIN_IMAGE_HEIGHT = 1024
MAX_IMAGE_HEIGHT = 1024
IMAGE_RESOLUTION_STEP = 64

MIN_IMAGE_COMPETITION_HOURS = 0.5
MAX_IMAGE_COMPETITION_HOURS = 1.0
QWEN_IMAGE_EXTRA_COMPETITION_HOURS = 0.5

FAL_KEY = os.getenv("FAL_KEY")
FAL_TIMEOUT_SECONDS = 300
FAL_IMAGE_GENERATION_CONCURRENCY = 20
FAL_PERSON_PROMPT_MODEL = "openrouter/router/vision"
FAL_PERSON_PROMPT_VLM = "google/gemini-2.5-flash"
FAL_TEXT_PROMPT_MODEL = "openrouter/router"
FAL_TEXT_PROMPT_LLM = "google/gemini-2.5-flash"
FAL_AVATAR_MODEL = "fal-ai/nano-banana-2/edit"
FAL_STYLE_MODEL_NANO_BANANA_2 = "fal-ai/nano-banana-2"
FAL_STYLE_MODEL_GPT_IMAGE_2 = "openai/gpt-image-2"
FAL_IMAGE_MODELS = (FAL_STYLE_MODEL_NANO_BANANA_2, FAL_STYLE_MODEL_GPT_IMAGE_2)
FAL_GPT_IMAGE_2_QUALITY = "medium"
FAL_NANO_BANANA_RESOLUTION = "1K"
FAL_IMAGE_OUTPUT_FORMAT = "png"

PROMPT_GEN_ENDPOINT = "https://llm.chutes.ai/v1/chat/completions"
IMAGE_GEN_ENDPOINT = "https://image.chutes.ai/generate"
NINETEEN_API_KEY = os.getenv("NINETEEN_API_KEY")

MIN_NUM_REWARD_FUNCTIONS = 2
MAX_NUM_REWARD_FUNCTIONS = 4

GET_AFFINE_GRPO_DATA_ENDPOINT = f"{PROD_CONTENT_BASE_URL}/affine-grpo-data/latest"
AFFINE_REWARD_FN_IDS = [
    "2226678e-df0d-42d0-8adb-551aec0ed88e",
    "dadf301b-14cc-4bb2-9bb8-7d658d29661c",
    "b5008828-8628-4ef5-b3f2-f77580028b67",
]
